import groovy.transform.CompileStatic
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
@CompileStatic
class App {

    void run() {
        def task = new Task("I'M VERY BUSY!")
        task.doSomething()
    }

    static void main(String[] args) {
        new App().run()
    }
}
